### ISSUE TITLE
rollup doesn't run with development

### ISSUE THREAD

**Issue by koo5** [codechips/svelte-starter-template#22]
i'm fairly new to js development, so anything's possible but could you confirm that this doesn't seem right:

```
koom@dev ~/test> npx degit codechips/svelte-starter-template cross-component-communication
npx: installed 1 in 1.942s
> cloned codechips/svelte-starter-template#master to cross-component-communication
koom@dev ~/test [127]> cd cross-component-communication && yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > rollup-plugin-html2@2.0.0" has unmet peer dependency "@types/html-minifier@^3.5.3".
[4/4] Building fresh packages...

success Saved lockfile.
Done in 14.47s.
koom@dev ~/test/cross-component-communication> node -v
v13.14.0
koom@dev ~/test/cross-component-communication> yarn start

yarn run v1.22.4
$ del-cli dist && NODE_ENV=development rollup --config --watch
Done in 0.91s.
```
now the interesting part:
```
koom@dev ~/test/cross-component-communication> env NODE_ENV=development node_modules/rollup/dist/bin/rollup --config --watch
koom@dev ~/test/cross-component-communication> 
```
^ it just quits immediately.
```
env NODE_ENV=something_else node_modules/rollup/dist/bin/rollup --config --watch
[!] Error: Unexpected token
rollup.config.js (45:4)
43:     name: 'bundle',
44:     file: 'dist/bundle.js',
45:     ,
        ^
46:     format: 'iife',
47:   },
Error: Unexpected token
    at error (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:5195:30)
    at Module.error (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:9657:16)
    at tryParse (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:9571:23)
    at Module.setSource (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:9963:30)
    at ModuleLoader.addModuleSource (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:18063:20)
    at ModuleLoader.fetchModule (/home/koom/test/cross-component-communication/node_modules/rollup/dist/shared/rollup.js:18117:9)
    at async Promise.all (index 0)

^C⏎                                                                                                                            koom@dev ~/test/cross-component-communication [SIGINT]> 
koom@dev ~/test/cross-component-communication [SIGINT]> sed -e s/"sourcemap: isDev"//g -i rollup.config.js
koom@dev ~/test/cross-component-communication> sed -e s/"sourcemap: isDev\,"//g  -i rollup.config.js
koom@dev ~/test/cross-component-communication> 
env NODE_ENV=something_else node_modules/rollup/dist/bin/rollup --config --watch
rollup v2.24.0
bundles src/main.js → dist/bundle.js...
created dist/bundle.js in 816ms

[2020-08-14 00:13:52] waiting for changes...
```

i also found: https://stackoverflow.com/questions/62840706/svelte-demo-template-does-not-start

**Comment by koo5** [comment]
turns out there can only be one `rollup --watch` at any time
